# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Fujun’s Blog
tagline:          ‘Petit à petit’
description:      'A place to record my thoughts on social movements and civil society and internet censorship'
url:              http://fujungao.info
baseurl:          /

author:
  name:           ‘Fujun GAO’
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
