# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Fujun’s Blog
tagline:          Petit à petit
description:      'A place to record my thoughts on the world’
url:              http://fujungao.info
baseurl:          /

author:
  name:           ‘Fujun GAO’
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
