# Site settings
title: A BLOG
header-img: "img/LuciolaCruciata.jpg"
tagline: "cn"  
description: "Fujun GAO| Thinking or Writing"  
baseurl: ""
url: "http://fujungao.info"  

# About/contact
owner: 
  name: " Fujun"
  email: fujungao@gmail.com
  bio: "Thinking or Writing"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/th.jpeg

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Fujun"
      header-img: "img/LuciolaCruciata.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 
  disqus :
      short_name : 

# Analytics and webmaster tools stuff goes here
google_analytics:UA-105687507-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

JB :
  analytics :
    provider : google 
    google : 
    tracking_id : 'UA-105687507-1'
