# Site settings
title: A BLOG
header-img: "img/LuciolaCruciata.jpg"
tagline: "cn"  
description: "Fujun GAO | Thinking or Writing"  
baseurl: ""
url: "http://fujungao.info"  
google_analytics: 'UA-87437901-1'
 

author:
  name: ‘Fujun’
  email: fujungao@gmail.com
  twitter_username: 
  facebook_username: fujungao.gao
  github_username:  
  linkedin_username: fujun-gao-5b91987b 

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
