# Site settings
title: A BLOG
description: "Fujun GAO| Thinking or Writing"  
url: 'http://www.fujungao.info
baseurl: '/'
google_analytics: 'UA-105687507-1'
#disqus_shortname: 
duoshuo_shortname: 

author:
  name: ‘Fujun’
  email: fujungao@gmail.com
  twitter_username: 
  facebook_username: 
  github_username:  
  linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
